print("I will count my books in my shelf:")
print("Maths",25+30)
print("Social",100-50*2%10)
print("Now I will count my chapters for exams:")
print(3+2+1-5+4%2-1/4+6)
print("Is it true that 3+2<5-7?")
print(3 + 2 < 5 - 7)
print("what is 3+2?", 3+2)
print("what is 6-10?", 6-10)
print("Oh, that 's my mistake it's correct")
print("How about some more.")
print("Is it great?", 8 > - 2)
print("Is it greater or equal?", 5 >= - 2)
print("Is it lesser or equal?", 5 <= - 2)
